name: Check PR

on:
  pull_request:
    branches:
      - main
      - develop
      - pre-develop

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }} #If any new push then it will canceled the old jobs
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      ANDROID_SDK_ROOT: /opt/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

      - name: Download emulator
        run: sdkmanager "system-images;android-30;google_apis;x86_64"

      - name: Create Android emulator
        run: echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force

      - name: Start emulator
        run: |
          nohup emulator -avd test -no-snapshot-save -no-window -gpu swiftshader_indirect -no-boot-anim -noaudio -no-snapshot &

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          adb shell settings put global window_animation_scale 0 &
          adb shell settings put global transition_animation_scale 0 &
          adb shell settings put global animator_duration_scale 0 &
          adb shell input keyevent 82 &

      - name: Run Android Instrumentation Tests
        run: ./gradlew connectedDebugAndroidTest
        if: always()  # Ensure this runs even if the previous step fails
