name: Release Deplyoment

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (alpha or beta)'
        required: true
        default: 'alpha'
      source_branch:
        description: 'Source branch for the release'
        required: true
        default: 'pre-develop'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set Git user.name and user.email
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_EMAIL }}"

      - name: Update CHANGELOG.md
        run: |
          chmod +x scripts/update_changelog.sh
          ./scripts/update_changelog.sh

      - name: Determine target branch
        id: determine_target
        run: |
          if [ "${{ github.event.inputs.release_type }}" == "alpha" ]; then
            echo "target_branch=develop" >> $GITHUB_ENV
          else
            echo "target_branch=main" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GIT_TOKEN }}
          source: ${{ github.event.inputs.source_branch }}
          target: ${{ env.target_branch }}
          title: '${{ github.event.inputs.release_type }} Release: ${{ github.sha }}'
          body: 'This PR is created by GitHub Actions for ${{ github.event.inputs.release_type }} release.'
          labels: ${{ github.event.inputs.release_type }}
